### ISSUE TITLE
'datetime.date' object has no attribute 'date'

### ISSUE THREAD

**Issue by qqrs** [henriquebastos/gnucash-to-beancount#11]
While attempting to convert my gnucash file, I ran into this error. I was able to reproduce it using the `data/sample.gnucash` file called by the projects `./tests.sh` script:
```
$ gnucash-to-beancount data/sample.gnucash
Traceback (most recent call last):
  File "/Users/zzz/.virtualenvs/bean/bin/gnucash-to-beancount", line 11, in <module>
    load_entry_point('gnucash-to-beancount', 'console_scripts', 'gnucash-to-beancount')()
  File "/Users/zzz/dev/bean/gnucash-to-beancount/src/gnucash_to_beancount/cli.py", line 39, in main
    entries = convert.load_entries(book)
  File "/Users/zzz/dev/bean/gnucash-to-beancount/src/gnucash_to_beancount/convert.py", line 16, in load_entries
    first_date = book.transactions[0].post_date.date()
AttributeError: 'datetime.date' object has no attribute 'date'
```

The error is occurring because three locations in the code appear to expect a `datetime.datetime` object, and call its `.date()` method to get a `datetime.date` object. But they are already receiving a `datetime.date` object.

Here is a (very rough) commit which works around the issue.

https://github.com/qqrs/gnucash-to-beancount/tree/fix_date_error

**Comment by PiQuer** [comment]
I ran into this bug after upgrading piecash, can only be reproduced with piecash >= 0.15.0. As a workaround I stay on piecash 0.14.1 for the moment.

**Comment by almereyda** [comment]
There is another proposed fix in #9.
