### ISSUE TITLE
decimal.InvalidOperation: [<class 'decimal.DivisionUndefined'>]

### ISSUE THREAD

**Issue by gour** [henriquebastos/gnucash-to-beancount#4]
Hello,

attempt to convert my personal Guncash file to Benacount results in:

```
gnucash-to-beancount personal.db > personal.beancount
Traceback (most recent call last):
  File "/home/gour/.virtualenvs/beancount/bin/gnucash-to-beancount", line 11, in <module>
    sys.exit(main())
  File "/home/gour/.virtualenvs/beancount/lib/python3.5/site-packages/gnucash_to_beancount/cli.py", line 39, in main
    entries = convert.load_entries(book)
  File "/home/gour/.virtualenvs/beancount/lib/python3.5/site-packages/gnucash_to_beancount/convert.py", line 35, in load_entries
    entries.append(TransactionWithPostings(txn))
  File "/home/gour/.virtualenvs/beancount/lib/python3.5/site-packages/gnucash_to_beancount/directives.py", line 140, in TransactionWithPostings
    return Transaction(txn, [Posting(split) for split in txn.splits])
  File "/home/gour/.virtualenvs/beancount/lib/python3.5/site-packages/gnucash_to_beancount/directives.py", line 140, in <listcomp>
    return Transaction(txn, [Posting(split) for split in txn.splits])
  File "/home/gour/.virtualenvs/beancount/lib/python3.5/site-packages/gnucash_to_beancount/directives.py", line 122, in Posting
    price = price_for(split)
  File "/home/gour/.virtualenvs/beancount/lib/python3.5/site-packages/gnucash_to_beancount/directives.py", line 110, in price_for
    number = abs(split.value / split.quantity)
decimal.InvalidOperation: [<class 'decimal.DivisionUndefined'>]
```

Any idea without having the source file?

**Comment by xentac** [comment]
I'm running into this same problem.

**Comment by gour** [comment]
@xentac I can confirm that your patch does help indeed. Thank you!

**Comment by qiwei123** [comment]
I meet the same question

**Comment by qiwei123** [comment]
` try:
            click_rate = "%.2f" % \
                         (row['clicks'] / row['impression'] * 100) + "%"
        except ZeroDivisionError:
            click_rate = ("%.2f" % 0.0) + "%"`
